version: '3'

services:
  gradesphere-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gradesphere-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://gradesphere-db:3306/grade_sphere_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - gradesphere-db

  gradesphere-db:
    image: mysql:latest
    container_name: gradesphere-db
    environment:
      MYSQL_DATABASE: grade_sphere_db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
